### ISSUE TITLE
poor documentation/instructions

### ISSUE THREAD

**Issue by andrewlorenz** [jonjamz/reactive-object#5]
the 'usage' section is very scant, and could well do with some more examples of how to declare/extend/modify/remove objects and their properties, and maybe how to use in conjunction with arrays.  thanks

**Comment by jonjamz** [comment]
I am no longer actively maintaining this library (it is pretty simple and works) so I would appreciate a PR here if you think you can make improvements.

There is not much in the way of examples because it is fairly self-explanatory. Use as you would a regular JS object and it works, subject to the browser compatibility of ES5 object features.

**Comment by andrewlorenz** [comment]
cool that's fine, I've actually found it as easy to use as you say - it just works.  Now I've used it I can't see any improvements for it, its a very neat solution.  cheers
